image: proboci/ubuntu-16.04-lamp:php7.2-nightly
steps:
  - name: Check versions..
    plugin: Script
    script:
      - echo "checking bower version..."
      - bower -version --allow-root
      - echo "checking grunt version..."
      - grunt -version
      - echo "checking gulp version..."
      - gulp -v
      - echo "checking yarn version..."
      - yarn --version
      - mysql --version
      - php -v
      - apache2 -v
      mysqlCnfOptions:
        max_allowed_packet: 24M
