image: proboci/ubuntu-16.04-lamp:php7.2-nightly
assets:
  - concrete5demo-2018-04-17.sql.gz
steps:
  - name: Probo Concrete5 LAMP site setup.
    plugin: LAMPApp
    database: concrete5demo-2018-04-17.sql.gz
    databaseName: concrete5demo
    databaseUser: concrete5demo
    databaseGzipped: true
    phpIniOptions:
      upload_max_filesize: 25M
      post_max_size: 25M
      memory_limit: 256M
