image: proboci/ubuntu:18.04-php7.3
steps:
  - name: Setting up test html.
    plugin: Script
    script: |
      mkdir /src/build
      echo "hello world" > /src/build/index.html
  - name: StaticApp Test..
    plugin: StaticApp
