image: proboci/ubuntu:18.04-php7.3
steps:
  - name: Download Drupal 8 Core latest.
    plugin: Script
    script: |
      mkdir /src/test
      echo "hello world" > /src/test/index.html
  - name: StaticApp Test
    plugin: StaticApp
    buildDirectory: test
    buildCommands: |
     /src/build
