assets: probo-credentials.yml
notifications:
  slack:
    - message: 'Custom message: New Probo build for project `$PROJECT_NAME` on branch `$BRANCH_NAME` at $BUILD_URL'
steps:
  - name: Test Connection
    plugin: Shell
    command: 'echo "Hello World!"'
